version: '3'
services:
  kaggle:
    build:
      context: .
      args:
        config_path: ./config/
        base_image: jupyter/pyspark-notebook
    user: root
    env_file:
      - ./config/.env
    ports:
      - 127.0.0.1:8888:8888 #$JUPYTER_PORT:$JUPYTER_PORT
    # entrypoint: ./config/run.sh